accounts/urls.py
from django.urls import path
from . import  views
from django.contrib.auth import views as auth_views

app_name = "accounts"

urlpatterns = [
    path("signup/",views.signup,name="signup"),
    path("login/",auth_views.LoginView.as_view(template_name = "accounts/login.html"),name="login"),
    path("logout/",auth_views.LogoutView.as_view(template_name="accounts/logout.html"),name="logout"),
    path("password_change/",auth_views.PasswordChangeView.as_view(template_name="accounts/password_change.html"),name="password_change"),
    path("password_change/done/",auth_views.PasswordChangeDoneView.as_view(template_name="accounts/password_change_done.html"),name="password_change_done"),
    path("password_reset/",auth_views.PasswordResetView.as_view(
        template_name = "accounts/password_reset.html",
        email_template_name = "accounts/password_reset_email.html"
        ),name="password_reset"),
    path("password_reset/done/",auth_views.PasswordResetDoneView.as_view(template_name = "accounts/password_reset_done.html"),name="password_reset_done"),
    path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(template_name = "accounts/password_reset_confirm.html"),name="password_reset_confirm"),
    path("reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name = "accounts/password_reset_complete.html"),name="password_reset_complete")
]

api/urls.py
from django.urls import path,include
from . import  views
from rest_framework.routers import DefaultRouter
from rest_framework_nested.routers import NestedSimpleRouter
router = DefaultRouter()

router.register("food",views.FoodViewSet,"food")
router.register("chef",views.ChefViewSet,"chef")
router.register("award",views.AwardsViewSet,"award")
router.register("link_of_chef",views.LinkViewSet,"link_of_chef")
router.register("restur_fetures",views.ResturFeaturesViewSet,"restur_fetures"),
router.register("image_gallery",views.imageGalleryViewSet,"image_gallery"),
router.register("event",views.EventViewSet,"event"),
router.register("package",views.PackageViewSet,"package"),
router.register("cart",views.CartViewSet,"cart"),
router.register("order",views.OrderViewSet,"order"),
router.register("table_booking",views.TableBookingViewSet,"table_booking"),
router.register("profiles",views.ProfileViewSet,"profiles"),

cart_router = NestedSimpleRouter(router,"cart")
cart_router.register("items",views.CartItemsViewSet,"items")

order_router = NestedSimpleRouter(router,"order")
order_router.register("items",views.OrderItemsViewSet,"items")


urlpatterns = [
    path("",include(router.urls)),
    path("",include(cart_router.urls)),
    path("",include(order_router.urls))
]

restur/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from pages.sitemaps import FoodSiteMap
sitemaps={
    "food":FoodSiteMap
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("",include("pages.urls",namespace="pages")),
    path("api/",include("api.urls")),
    path("auth/",include("djoser.urls")),
    path("auth/",include("djoser.urls.jwt")),
    path("sitemap.xml",sitemap,{"sitemaps":sitemaps},name="django.contrib.sitemaps.views.sitemap")
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
class UserCreateForm(UserCreationForm):
    address = forms.CharField(max_length=400)
    phone_number = forms.CharField(max_length=15)
    class Meta(UserCreationForm.Meta):
        fields = ["username","first_name","email","password1","password2"]

accounts/views.py
from django.shortcuts import render,redirect
from .forms import UserCreateForm
from django.contrib.auth import login
from pages.models import Cart,Profile
def signup(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            Cart.objects.create(owner = user)
            Profile.objects.create(
                user = user,
                address=form.cleaned_data["address"],
                phone_number=form.cleaned_data["phone_number"])
            login(request,user=user)

            return redirect(request.GET.get("next","/"))
    else:
        form = UserCreateForm()
    return render(request,"accounts/signup.html",{"form":form})

templates/accounts/login.html
{% extends "base.html" %}

{% block title %} login {% endblock %}

{% block main %}
    <h1>login now</h1>

    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="login"  class="btn-book-table">
    </form>
    <p> or <a href="{% url 'accounts:signup' %}">sign up</a></p>

    <script>
        const inputs = document.getElementsByTagName("input")
        Array.from(inputs).forEach(input=>{
            if (input.type  != "submit" ){
                input.className = "form-control"
                input.style.color = "var(--heading-color)"
            }
        })
    </script>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
        .btn-book-table{
        background: var(--accent-color);
        color: var(--contrast-color);
        border: 0;
        padding: 14px 38px;
        font-weight: 600;
        font-size: 0.95rem;
        border-radius: 4px;
        transition: all 0.3s 
    ease;
        margin-top: 1rem;
        }
    </style>

{% endblock %}

templates/accounts/logout.html
{% extends "base.html" %}

{% block title %} logout {% endblock %}

{% block main %}
    <h1>logout</h1>
    <p>you can <a href="{% url 'accounts:login' %}">login now</a></p>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
    </style>

{% endblock %}

templates/accounts/password_change.html
{% extends "base.html" %}

{% block title %} Password change {% endblock %}

{% block main %}
    <h1>Password change</h1>
    <p>Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.</p>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="change password"  class="btn-book-table">
    </form>

    <script>
        const inputs = document.getElementsByTagName("input")
        Array.from(inputs).forEach(input=>{
            if (input.type  != "submit" ){
                input.className = "form-control"
                input.style.color = "var(--heading-color)"
            }
        })
    </script>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
        .btn-book-table{
        background: var(--accent-color);
        color: var(--contrast-color);
        border: 0;
        padding: 14px 38px;
        font-weight: 600;
        font-size: 0.95rem;
        border-radius: 4px;
        transition: all 0.3s 
    ease;
        margin-top: 1rem;
        }
    </style>

{% endblock %}

templates/accounts/password_change_done.html
{% extends "base.html" %}

{% block title %} Password change successful {% endblock %}

{% block main %}
    <h1>Password change successful</h1>
    <p>Your password was changed.</p>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
    </style>

{% endblock %}

templates/accounts/password_reset.html
{% extends "base.html" %}

{% block title %} password reset {% endblock %}

{% block main %}
    <h1>password reset</h1>

    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="reset password"  class="btn-book-table">
    </form>

    <script>
        const inputs = document.getElementsByTagName("input")
        Array.from(inputs).forEach(input=>{
            if (input.type  != "submit" ){
                input.className = "form-control"
                input.style.color = "var(--heading-color)"
            }
        })
    </script>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
        .btn-book-table{
        background: var(--accent-color);
        color: var(--contrast-color);
        border: 0;
        padding: 14px 38px;
        font-weight: 600;
        font-size: 0.95rem;
        border-radius: 4px;
        transition: all 0.3s 
    ease;
        margin-top: 1rem;
        }
    </style>

{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block title %} password reset done {% endblock %}

{% block main %}
    <h1>password reset done</h1>
    <p>you can <a href="{% url 'accounts:login' %}">login now</a></p>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
    </style>

{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block title %} paswsword reset confirm {% endblock %}

{% block main %}
    <h1>paswsword reset confirm</h1>

    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="reset the password"  class="btn-book-table">
    </form>

    <script>
        const inputs = document.getElementsByTagName("input")
        Array.from(inputs).forEach(input=>{
            if (input.type  != "submit" ){
                input.className = "form-control"
                input.style.color = "var(--heading-color)"
            }
        })
    </script>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
        .btn-book-table{
        background: var(--accent-color);
        color: var(--contrast-color);
        border: 0;
        padding: 14px 38px;
        font-weight: 600;
        font-size: 0.95rem;
        border-radius: 4px;
        transition: all 0.3s 
    ease;
        margin-top: 1rem;
        }
    </style>

{% endblock %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block title %} password reset done {% endblock %}

{% block main %}
    <h1>password reset done</h1>
    <p>there is an  email sended to you to change password</p>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
    </style>

{% endblock %}

templates/accounts/password_reset_email.html
you can reset your password now from this link  below:

{{protocol }}://{{domain}}{% url  "password_reset_confirm" uidb64=uid token=token %}

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %} sign up {% endblock %}

{% block main %}
    <h1>sign up  now</h1>

    <form method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Sign up"  class="btn-book-table">
    </form>

    <script>
        const inputs = document.getElementsByTagName("input")
        Array.from(inputs).forEach(input=>{
            if (input.type  != "submit" ){
                input.className = "form-control"
                input.style.color = "var(--heading-color)"
            }
        })
    </script>
    <style>
        main{
            width: 80%;
            justify-self: center;
            margin: 100px 60px;
        }
        .btn-book-table{
        background: var(--accent-color);
        color: var(--contrast-color);
        border: 0;
        padding: 14px 38px;
        font-weight: 600;
        font-size: 0.95rem;
        border-radius: 4px;
        transition: all 0.3s 
    ease;
        margin-top: 1rem;
        }
    </style>

{% endblock %}